# Generated by Django 2.1 on 2018-09-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='metadata',
            field=models.ManyToManyField(related_name='equipments', to='metadata.Metadata'),
        ),
    ]
